### ISSUE TITLE
Unable to append middleware

### ISSUE THREAD

**Issue by elyerinfox** [upgate/laravel-jsonrpc#11]
Hi There,

While working on a project I have encountered a problem while attempting to assign 3 middelwares to my router. I am using version `0.3.2` as provided by composer and receive the following error while attempting to replicate the example in some way for my use cases.

---

The error:
```-
(1/1) ErrorCall to undefined method Upgate\LaravelJsonRpc\Server\Router::setMiddlewares()
--
in rpc.php line 18
```

---

My `routes/rpc.php`:
```php
$router->post('/rpc', function (Request $request) use ($jsonRpcServer) {
    $jsonRpcServer->router()
        ->setMiddlewares(['auth', '2fa', 'ssp'])
        ->bindController('server', 'Controller');
    return $jsonRpcServer->run($request);
});
```

---

Do you have any idea how I can work around this? providing the middlewares inside of the controller constructor does not seem to work, and I'm also unsure if this is an actual bug in the code.

Regards,
Ely Haughie

**Comment by elyerinfox** [comment]
Further update:

After going through the class where the method is defined, it seems that the acutal function declaration is `addMiddlewares` when the example contains `setMiddleware`.

It seems to work after altering my code, and I just wanted to let you know!

**Comment by kbaryshnikov** [comment]
The method is actually called addMiddlewares not setMiddlewares.

Thanks for pointing out the mistake in README, just fixed that.
