### ISSUE TITLE
Inconsistent state of `Server` and `Binding`

### ISSUE THREAD

**Issue by s-chizhik** [upgate/laravel-jsonrpc#34]
Hello!
I've noticed a little problem, which appears when the `Router::resolve` method is being called.

This method finds the appropriate controller or method `Binding` and resolves specific `Route`.

The problem is that `Binding` can be created before `Router` gets knowledge about middleware aliases. So `Binding` will contain different middleware aliases than `Router`.

**Doesn't work properly:**
```PHP
$server->router()->bindController(...); // creates Binding here
$server->registerMiddlewareAliases(...); // sets middleware aliases to router, Bindings won't know about them
```

**Works fine:**
```PHP
$server->registerMiddlewareAliases(...); // sets middleware aliases
$server->router()->bindController(...); // new Binding will get actual aliases
```

Currently, I didn't research a good solution. As an option, I suppose it would be good to try:
- remove `MiddlewaresCollection` from `Binding`s constructor
- pass them during calling `Router::resolve`

```PHP
// \Upgate\LaravelJsonRpc\Server\Router::resolve
public function resolve(string $method): RouteContract
{
    return $this
        ->findBinding($method)
        ->setMiddlewaresCollection($this->middlewaresCollection)
        ->resolveRoute($method);
}
```

Also, I didn't research the problem deeply, so I can't say for sure, is that a problem with an inconsistent state exists only for middleware aliases.

I appreciate any feedback you may have.

**Comment by kbaryshnikov** [comment]
Could you please provide a test case?

I've pushed the feature/aliases-late-binding branch. My attempt to reproduce is here: tests/MiddlewareAliasLateBindingTest.php, but it seems to be working whatever the order is. Could you please adjust the test to reproduce the issue? Thanks!

**Comment by s-chizhik** [comment]
Yes, sure.

Indeed, I was mistaken in saying about bindController. For only `Router::bindController()` it works fine.

I did a little investigation and noticed, that in the case when we use `Router::bindController()` all works fine because it contains the same object `MiddlewaresCollection`, and no matter where we add bindings.

But it doesn't work for groups, because `Router::group()` makes a clone of the middleware collection and it will not receive updated aliases anymore.

I've reproduced this case, you can check it here https://github.com/upgate/laravel-jsonrpc/commit/13ea9d2e51836842f9437296b0cfe5db5fb4fd34

**Comment by kbaryshnikov** [comment]
Could you please review #35?
Sure, it isn't the most elegant fix, but it's the best I could come up with to keep BC (more or less).

**Comment by s-chizhik** [comment]
Thank you for your PR. I’ll look through it as soon as possible.

**Comment by s-chizhik** [comment]
@kbaryshnikov would you please review my comment on your PR #35?

**Comment by s-chizhik** [comment]
@kbaryshnikov thank you 🙏
