### ISSUE TITLE
Incompatible method setPayload in Server class with ServerInterface contract

### ISSUE THREAD

**Issue by TheLazzziest** [upgate/laravel-jsonrpc#5]
Hello, i have the issue with installing you library in Laravel Framework 5.5. After I defined routing in RouteServiceProvider according to your readme file and try to run the server, the following error appeared: 
Declaration of Upgate\LaravelJsonRpc\Server\Server::setPayload(string $payload): Upgate\LaravelJsonRpc\Server\void must be compatible with Upgate\LaravelJsonRpc\Contract\ServerInterface::setPayload(  
  string $payload): Upgate\LaravelJsonRpc\Contract\void

I look at Server class and it seems the implementation of the contract is correct, but it can't figure out where the error is. Thanks for help in advance.

**Comment by kbaryshnikov** [comment]
The library requires PHP 7.1. You seem to be using PHP 7.0.
