### ISSUE TITLE
Handling exception during resolving request

### ISSUE THREAD

**Issue by TheLazzziest** [upgate/laravel-jsonrpc#7]
When I use [jwt](https://github.com/tymondesigns/jwt-auth) library, I add authentication middleware from jwt  to group of routes. When authentication is failed, middleware throws exception UnauthorizedHttpException, but server returns internal server error. I implement my own middleware and exception which inherits from JsonRpcException, but not everything can be rewrite in a such manner.
Maybe it will be better to add some flexibility during exceptoin handling. What do you think?

**Comment by kbaryshnikov** [comment]
See `Upgate\LaravelJsonRpc\Server\Server::onException()`.

https://github.com/upgate/laravel-jsonrpc/blob/0.2.2/src/Server/Server.php#L86
https://github.com/upgate/laravel-jsonrpc/blob/0.2.2/tests/ServerTest.php#L161
